import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          blue: '#3b82f6',
          dark: '#1e3a8a',
          light: '#eff6ff',
          gray: '#f3f4f6',
          text: '#374151',
          orange: '#f59e0b',
          red: '#ef4444',
          green: '#10b981',
        },
        "secondary-fixed": "#6bff8f",
        "on-surface-variant": "#444749",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        secondary: "#006e2f",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed": "#001a42",
        "primary-container": "#f8fafc",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#adc6ff",
        "primary-fixed-dim": "#c4c7c9",
        "primary-fixed": "#e0e3e5",
        "tertiary-fixed": "#d8e2ff",
        "inverse-primary": "#c4c7c9",
        "outline-variant": "#c4c7c9",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#4ae176",
        "on-tertiary-fixed-variant": "#004395",
        "on-secondary-container": "#007432",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#444749",
        "on-secondary": "#ffffff",
        outline: "#747779",
        "secondary-container": "#6bff8f",
        background: "#f8f9ff",
        "surface-container-low": "#eff4ff",
        primary: "#5c5f61",
        tertiary: "#005ac2",
        "on-secondary-fixed-variant": "#005321",
        "tertiary-container": "#faf9ff",
        "error-container": "#ffdad6",
        "surface-tint": "#5c5f61",
        "on-surface": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#707375",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#002109",
        surface: "#f8f9ff",
        error: "#ba1a1a",
        "on-primary-fixed": "#191c1e",
        "surface-variant": "#d3e4fe",
        "on-tertiary-container": "#1d6ee2",
        "inverse-surface": "#213145",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "64px",
        sm: "12px",
        margin: "32px",
        base: "8px",
        md: "24px",
        xs: "4px",
        gutter: "24px",
        lg: "40px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      boxShadow: {
        card: '0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03)',
      },
      keyframes: {
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'spin-slow': 'spin-slow 3s linear infinite',
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "data-point": [
          "28px",
          { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        h1: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
